### ISSUE TITLE
Please upload to PyPi

### ISSUE THREAD

**Issue by xboxone08** [Will-777/spawn_mobs_mcpi#6]

**Comment by leha-code** [comment]
This probably isn't happening, but if you really need it you can use [mcpi-mobs](https://pypi.org/project/mcpi-mobs)

**Comment by leha-code** [comment]
@xboxone08 docs at https://mcpi-utils.readthedocs.io/en/latest/index.html

**Comment by xboxone08** [comment]
@leha-code thanks!
